"""TRANCEatables simulation domain core."""

from .feasibility import FeasibilityDecision, evaluate_delivery
from .models import DeliveryRequest, FoodHandling, RobotState
from .meal_plan import (
    DuplicateMealPlanError,
    MealPlanEligibilityError,
    MealPlanEvent,
    MealPlanNotFoundError,
    MealPlanService,
    SimulatedMealPlan,
    SQLiteMealPlanRepository,
)
from .nutrient_solver import (
    MealConstraintSolution,
    NutrientSolverError,
    solve_meal_references,
)
from .order_state import InvalidTransition, Order, OrderStatus, can_transition
from .repository import (
    ConcurrentUpdateError,
    DuplicateOrderError,
    OrderEvent,
    OrderNotFoundError,
    SQLiteOrderRepository,
)
from .service import OrderService
from .robot_mission import (
    ALLOWED_MISSION_TRANSITIONS,
    InvalidMissionTransition,
    MissionStatus,
    RobotMission,
    RobotStatus,
    SimulatedRobot,
    can_transition_mission,
)
from .robot_mission_repository import (
    DuplicateMissionError,
    DuplicateRobotError,
    MissionEligibilityError,
    MissionEvent,
    MissionNotFoundError,
    RobotNotFoundError,
    SafetyEvent,
    SQLiteRobotMissionRepository,
    TelemetryRecord,
)
from .robot_mission_service import RobotMissionService
from .serving_candidate import (
    DuplicateServingCandidateError,
    DuplicateServingCandidateReviewError,
    FoodServingCandidate,
    ServingCandidateEligibilityError,
    ServingCandidateEvent,
    ServingCandidateInput,
    ServingCandidateNotFoundError,
    ServingCandidateReview,
    ServingCandidateService,
    SQLiteServingCandidateRepository,
)
from .serving_revision import (
    DuplicateServingRevisionError,
    ServingCandidateRevision,
    ServingRevisionNotFoundError,
    ServingRevisionReview,
    ServingRevisionService,
    SQLiteServingRevisionRepository,
)
from .sheety_reference import (
    RestaurantReference,
    SheetyReferenceClient,
    SheetyReferenceError,
    SheetyReferenceSnapshot,
)

__all__ = [
    "ALLOWED_MISSION_TRANSITIONS",
    "ConcurrentUpdateError",
    "DeliveryRequest",
    "DuplicateMealPlanError",
    "DuplicateMissionError",
    "DuplicateOrderError",
    "DuplicateRobotError",
    "DuplicateServingCandidateError",
    "DuplicateServingCandidateReviewError",
    "DuplicateServingRevisionError",
    "FeasibilityDecision",
    "FoodHandling",
    "FoodServingCandidate",
    "InvalidMissionTransition",
    "InvalidTransition",
    "MissionEligibilityError",
    "MissionEvent",
    "MissionNotFoundError",
    "MissionStatus",
    "MealConstraintSolution",
    "MealPlanEligibilityError",
    "MealPlanEvent",
    "MealPlanNotFoundError",
    "MealPlanService",
    "NutrientSolverError",
    "Order",
    "OrderEvent",
    "OrderNotFoundError",
    "OrderService",
    "OrderStatus",
    "RobotMission",
    "RobotMissionService",
    "RobotNotFoundError",
    "RobotState",
    "RobotStatus",
    "RestaurantReference",
    "SafetyEvent",
    "ServingCandidateEligibilityError",
    "ServingCandidateEvent",
    "ServingCandidateInput",
    "ServingCandidateNotFoundError",
    "ServingCandidateReview",
    "ServingCandidateRevision",
    "ServingCandidateService",
    "ServingRevisionNotFoundError",
    "ServingRevisionReview",
    "ServingRevisionService",
    "SheetyReferenceClient",
    "SheetyReferenceError",
    "SheetyReferenceSnapshot",
    "SimulatedMealPlan",
    "SimulatedRobot",
    "SQLiteMealPlanRepository",
    "SQLiteOrderRepository",
    "SQLiteRobotMissionRepository",
    "SQLiteServingCandidateRepository",
    "SQLiteServingRevisionRepository",
    "TelemetryRecord",
    "can_transition",
    "can_transition_mission",
    "evaluate_delivery",
    "solve_meal_references",
]
